---
- name: Create AWS Key Pair
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create key pair
      amazon.aws.ec2_key:
        name: sample
        region: us-east-1
      register: keyout

    #- name: print key
    # debug:
    #    var: keyout

    - name: save key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample.pem
      when: keyout.changed == True


    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "my-ansible-server"
        key_name: "sample"
        instance_type: t2.micro
        image_id: ami-0354c98ae10b02961
        region: us-east-1
        wait: true
        count: 1
        security_group: default
      register: ec2_instance

    - name: Display instance information
      ansible.builtin.debug:
        var: ec2_instance
